* clos-sweeper

A toy mine sweeper written in Common Lisp

**  License

Public Domain

** Libraries

https://github.com/bohonghuang/cl-gtk4

https://lispcookbook.github.io/cl-cookbook/clos.html

** Setup

Make sure SBCL is installed

Make sure you have quicklisp and ultralisp installed.

https://www.quicklisp.org/beta/

https://ultralisp.org/

Make sure you have gtk4 libraries installed.

*** Linux
On Ubuntu like Linux you run: sudo apt install libgtk-4-dev

*** Windows
On Windows 11 with MSYS2 run MINGW64 terminal and execute:
#+begin_example
  pacman -S mingw-w64-x86_64-gtk4 mingw-w64-x86_64-cairo mingw-w64-x86_64-gobject-introspection
#+end_example

Edit environment variables for your account and add path to the dll files
installed in the previous step

On my system it is:
#+begin_example
c:/msys64/mingw64/bin
c:/"Program Files"/Emacs/emacs-29.1/bin
#+end_example

also I have a *.cmd that starts Emacs with correct environment setting

#+begin_example
set PATH=c:/msys64/mingw64/bin;c:/msys64/usr/bin;%PATH%

set PKG_CONFIG_PATH=c:/msys64/mingw64/lib/pkgconfig

C:\"Program Files"\Emacs\emacs-29.1\bin\runemacs.exe
#+end_example

That allowed me to run Emacs, slime and play few games without crashing that I
had before I started looking for the correct environment.

There is no guarantee it will work smoothly on your Windows. If you ahve any
suggestions or questions please let me know.

** Running
Run the following

*** Windows
#+begin_example
(push #p"c:/Users/jacek/Programming/Lisp/clos-sweeper/" asdf:*central-registry*)
(ql:quickload :clos-sweeper)
(clos-sweeper::main)
#+end_example

*** Linux
#+begin_example
(push #p"~/Programming/Lisp/clos-sweeper/" asdf:*central-registry*)
(ql:quickload :clos-sweeper)
(clos-sweeper::main)
#+end_example

** Testing

*** in the terminal
#+begin_example
sbcl --load  ~/Programming/Lisp/clos-sweeper/testing.lisp
#+end_example

*** in the REPL
#+begin_src lisp
  (push #p"~/Programming/Lisp/clos-sweeper/" asdf:*central-registry*)
  (ql:quickload :clos-sweeper/tests)
  (asdf:test-system :clos-sweeper/tests)
#+end_src

Some tests may write a snapshot of the canvas. It goes to /tmp/ on Linux
and on Windows it goes to: C:\Users\jacek\AppData\Local\Temp.
That folder does not get cleared on reboot as /tmp/ on Linux.
You have to clear the ~*.png~ files manually.
** Not implemented

*** Menu
Only starting game at different sizes and quit and about dialog work.

*** Icons
No icons yet, the state of the game is indicated by colour of the tiles.
