* clos-sweeper

A toy mine sweeper written in Common Lisp

**  License

Public Domain

** Libraries

https://github.com/bohonghuang/cl-gtk4

https://lispcookbook.github.io/cl-cookbook/clos.html

** Running it

Make sure SBCL is installed

Make sure you have quicklisp and ultralisp installed.

https://www.quicklisp.org/beta/

https://ultralisp.org/

Make sure you have gtk4 libraries installed.

On Ubuntu like Linux you run: sudo apt install libgtk-4-dev

On Windows 11 with MSYS2 run MINGW64 terminal and execute:
 pacman -S mingw-w64-x86_64-gtk4 mingw-w64-x86_64-cairo mingw-w64-x86_64-gobject-introspection 

Edit environment variables for your account and add path to the dll files installect in the previous step
On my system it is:
#+begin_example
c:/msys64/mingw64/bin
c:/"Program Files"/Emacs/emacs-29.1/bin
#+end_example

also I have a *.cmd that starts Emacs with correct setting

#+begin_example
set PATH=c:/msys64/mingw64/bin;c:/msys64/usr/bin;%PATH%

set PKG_CONFIG_PATH=c:/msys64/mingw64/lib/pkgconfig

C:\"Program Files"\Emacs\emacs-29.1\bin\runemacs.exe
#+end_example

That allowed me to play few games without crashing that I had before I started looking for the correct environmet.



Run the following

#+begin_example
(push #p"c:/Users/jacek/Programming/Lisp/clos-sweeper/" asdf:*central-registry*)
;; or
(push #p"~/Programming/Lisp/clos-sweeper/" asdf:*central-registry*)
(ql:quickload :clos-sweeper)
(clos-sweeper::main)
#+end_example

** Testing

*** in the terminal
#+begin_example
sbcl --load  ~/Programming/Lisp/clos-sweeper/testing.lisp
#+end_example

*** in the REPL
#+begin_src lisp
  (push #p"~/Programming/Lisp/clos-sweeper/" asdf:*central-registry*)
  (asdf:test-system :clos-sweeper/tests)
#+end_src

** Not implemented

*** Menu
Only starting game at different sizes and quit and about work.

*** Icons
No icons yet, the state of the game is indicated by colour of the tiles.
